apiVersion: v1
kind: Service
metadata:
  name: obsidian-mcp-server
  namespace: claude
  labels:
    app: obsidian-mcp-server
spec:
  type: NodePort
  selector:
    app: obsidian-mcp-server
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30237
      protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
